### PR TITLE
Fix clearing output of previous executions

### LINKED ISSUE #71: Output window unable to be closed while multiple output windows poping up
I am not sure if this is a bug or if a new feature to make. 

The problem is when you try to run MagmaReevaluateCell while the previous output window is not closed, then there will be two windows opened. Then the previous window will never close and I don't know how to access it as well. 

So maybe the solution can be:
1. Automatically close the current output window right after re-evaluating the cell.
2. Provide a method access to the previous output window as a kind of modified version of :noautocmd MagmaEnterOutput 

Not an essential problem, not affecting my love for using Magma.

### PR DESCRIPTION
**Pull request by LoipesMas**
Fixes #71, #68, #50
Probably also #63, but I couldn't get plots to show, so maybe it's something else
Probably #60 as well, because it looks like a duplicate of #50, but I'm not sure

Just makes sure that all outputs that are overlapping with currently selected span are deleted.
And a small fix to `delete_cell`: `update_interface` doesn't close deleted outputs, so we clear it explicitly on deletion

### CODE REVIEW

**Comment by WhiteBlackGoose** [comment]
Seems to be working for me so far. Thanks

**Comment by usmcamp0811** [comment]
Yea I concur.. certified working on my machine! good job!

**Comment by Ch0ronomato** [comment]
can we merge this?

**Comment by WhiteBlackGoose** [comment]
Thanks!

**Pull request merged**
