### PR TITLE
Add MagmaEnterOutput

### PR DESCRIPTION
**Pull request by tzachar**
Allow users to enter the output window
Also decorate the window with borders

### CODE REVIEW

**Comment by tzachar** [comment]
Hi @dccsillag 
Any chance of merging this?
Have been using it for the past 2 weeks and found it very useful.

**Comment by dccsillag** [comment]
Yeah, I will be merging this; I just haven't done so because I want to check carefully if everything is fine with the window borders you've enabled, and have been quite busy with other things.

I'll try to check things out and merge in the next fews days.

**Comment by tzachar** [comment]
@dccsillag 
ping

**Comment by dccsillag** [comment]
Hey, I'm going to tackle this now.
I'll cherry pick the window borders out of this PR, and reimplement them with a configuration toggle (I'll still mention you in the commit(s)).

**Comment by dccsillag** [comment]
All done with edf60f0b809c88dab3a4ea492e0dcf80fc00af5b.

**Comment by tzachar** [comment]
10x

**Comment by WhiteBlackGoose** [comment]
Hi, thanks for this, but for some reason it won't switch to the window for me:
> pynvim.api.common.NvimError: Vim:E5555: API call: Failed to switch to window 1011

I suspect it's because it closes the window and then tries to switch. Any idea how to fix it?

**Comment by WhiteBlackGoose** [comment]
FWIW, since likely no one will respond, I made a workaround for it by copying the traceback into clipboard automatically

[my fork](https://github.com/WhiteBlackGoose/magma-nvim-goose)

**Pull request merged**
